module OslValkey
  module Cookbook
    module Helpers
      # Whether the config a marker guards was already seeded at this
      # config_version. Both daemons rewrite their own config at
      # runtime, so the file's own content is not comparable after the
      # first rewrite: the marker records what chef last seeded, and
      # bumping config_version is what triggers a re-seed.
      def valkey_config_seeded?(marker, config_version)
        ::File.exist?(marker) && ::File.read(marker).strip == config_version.to_s
      end

      # The valkey package only ships in AppStream from EL 9.7 on
      def osl_valkey_supported?
        platform_family?('rhel') && Gem::Version.new(node['platform_version']) >= Gem::Version.new('9.7')
      end

      def osl_valkey_unit(name, instance)
        instance ? "valkey@#{name}" : 'valkey'
      end

      def osl_valkey_conf(name, instance)
        instance ? "/etc/valkey/#{name}.conf" : '/etc/valkey/valkey.conf'
      end

      # osl-prometheus finds servers by these markers, so keep the naming stable
      def osl_valkey_marker(conf)
        ::File.join(::File.dirname(conf), ".#{::File.basename(conf)}.chef")
      end

      # config with maxmemory/save folded in; an empty save must render as save ""
      def osl_valkey_config(config, maxmemory, save)
        c = config.to_h.transform_keys(&:to_s)
        c['maxmemory'] = maxmemory if maxmemory
        c['save'] = save if save
        c['save'] = '""' if c.key?('save') && ['', '""'].include?(c['save'].to_s)
        c
      end

      # An unset save still forks: valkey's compiled-in default snapshots
      def osl_valkey_forks?(appendonly, save, replicaof, min_replicas_to_write)
        appendonly || save != '""' || !replicaof.nil? || !min_replicas_to_write.nil?
      end

      # Where a local client (the exporter) reaches the server
      def osl_valkey_host(bind)
        host = bind.to_s.split.first.to_s.delete_prefix('-')
        host.empty? || %w(* 0.0.0.0 ::).include?(host) ? '127.0.0.1' : host
      end

      def osl_valkey_restart_drop_in
        "# Generated by Chef\n[Service]\nRestart = on-failure\nRestartSec = 5s\n"
      end
    end
  end
end

Chef::DSL::Recipe.include ::OslValkey::Cookbook::Helpers
Chef::Resource.include ::OslValkey::Cookbook::Helpers
