require_relative '../../spec_helper'

describe 'valkey_test::server_sentinel' do
  ALL_PLATFORMS.each do |p|
    context "#{p[:platform]} #{p[:version]}" do
      cached(:chef_run) do
        ChefSpec::SoloRunner.new(
          p.dup.merge(step_into: %w(osl_valkey osl_valkey_sentinel))
        ).converge(described_recipe)
      end

      it 'converges successfully' do
        expect { chef_run }.to_not raise_error
      end

      it do
        is_expected.to create_osl_valkey('default').with(
          pass: 'valkey-test',
          bind: '127.0.0.1',
          appendonly: true,
          maxmemory_policy: 'noeviction',
          config: { 'tcp-keepalive' => 60 }
        )
      end
      it do
        is_expected.to create_osl_valkey_sentinel('testlocks').with(
          pass: 'valkey-test',
          monitor_host: '127.0.0.1',
          quorum: 1,
          down_after_ms: 3000,
          failover_timeout_ms: 30_000
        )
      end

      it { is_expected.to accept_osl_firewall_port('valkey').with(ports: %w(6379), osl_only: true) }
      it { is_expected.to accept_osl_firewall_port('valkey_sentinel').with(ports: %w(26379), osl_only: true) }
      it { is_expected.to install_package 'valkey' }
      it { is_expected.to apply_sysctl('vm.overcommit_memory').with(value: '1') }

      %w(valkey valkey-sentinel).each do |svc|
        it { is_expected.to create_directory("/etc/systemd/system/#{svc}.service.d") }
        it do
          is_expected.to create_file("/etc/systemd/system/#{svc}.service.d/restart.conf").with(
            content: "# Generated by Chef\n[Service]\nRestart = on-failure\nRestartSec = 5s\n"
          )
        end
        it do
          expect(chef_run.file("/etc/systemd/system/#{svc}.service.d/restart.conf")).to \
            notify("execute[#{svc}: daemon-reload]").to(:run).immediately
        end
      end
      it { is_expected.to_not create_systemd_unit('valkey@.service') }
      it do
        expect(chef_run.node['osl-valkey']['instances']['default'].to_h).to eq(
          'config' => '/etc/valkey/valkey.conf', 'host' => '127.0.0.1', 'port' => 6379
        )
      end

      %w(valkey valkey-sentinel).each do |svc|
        it { is_expected.to enable_service svc }
        it { is_expected.to start_service svc }
      end

      it do
        expect(chef_run.template('/etc/valkey/valkey.conf')).to \
          notify('service[valkey]').to(:restart).immediately
      end
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^requirepass valkey-test$/) }
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^masterauth valkey-test$/) }
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^appendonly yes$/) }
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^maxmemory-policy noeviction$/) }
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^tcp-keepalive 60$/) }
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^bind 127\.0\.0\.1$/) }
      it { is_expected.to_not render_file('/etc/valkey/valkey.conf').with_content(/^replicaof/) }
      it { is_expected.to_not render_file('/etc/valkey/valkey.conf').with_content(/^min-replicas-to-write/) }

      it do
        expect(chef_run.template('/etc/valkey/sentinel.conf')).to \
          notify('service[valkey-sentinel]').to(:restart).immediately
      end
      it do
        is_expected.to create_template('/etc/valkey/sentinel.conf').with(
          owner: 'valkey',
          group: 'valkey',
          mode: '0640',
          sensitive: true
        )
      end
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^port 26379$/) }
      # No requirepass set, so sentinel takes any client the firewall
      # admits; the template says so rather than claiming auth is
      # impossible.
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^protected-mode no$/) }
      it { is_expected.to_not render_file('/etc/valkey/sentinel.conf').with_content(/^requirepass/) }
      it { is_expected.to_not render_file('/etc/valkey/sentinel.conf').with_content(/^bind/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^sentinel deny-scripts-reconfig yes$/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^sentinel resolve-hostnames yes$/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^sentinel monitor testlocks 127\.0\.0\.1 6379 1$/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^sentinel auth-pass testlocks valkey-test$/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^sentinel down-after-milliseconds testlocks 3000$/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^sentinel failover-timeout testlocks 30000$/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^sentinel parallel-syncs testlocks 1$/) }

      %w(/etc/valkey/.valkey.conf.chef /etc/valkey/.sentinel.conf.chef).each do |marker|
        it { is_expected.to create_file(marker).with(content: "1\n") }
      end

      it { is_expected.to create_cookbook_file('/usr/local/lib/valkey_tools.rb').with(mode: '0644') }
      %w(valkey-status valkey-failover).each do |tool|
        it { is_expected.to create_cookbook_file("/usr/local/bin/#{tool}").with(mode: '0755') }
      end

      # Seed-once guard: a marker at the current config_version leaves
      # both configs alone, since the daemons own them at runtime.
      context 'already seeded' do
        cached(:chef_run) do
          ChefSpec::SoloRunner.new(
            p.dup.merge(step_into: %w(osl_valkey osl_valkey_sentinel))
          ).converge(described_recipe)
        end

        before do
          allow(File).to receive(:exist?).and_call_original
          allow(File).to receive(:read).and_call_original
          %w(/etc/valkey/.valkey.conf.chef /etc/valkey/.sentinel.conf.chef).each do |marker|
            allow(File).to receive(:exist?).with(marker).and_return(true)
            allow(File).to receive(:read).with(marker).and_return("1\n")
          end
        end

        it { is_expected.to_not create_template '/etc/valkey/valkey.conf' }
        it { is_expected.to_not create_template '/etc/valkey/sentinel.conf' }
      end

      # A bumped config_version re-seeds over a stale marker.
      context 'seeded at an older config_version' do
        cached(:chef_run) do
          ChefSpec::SoloRunner.new(
            p.dup.merge(step_into: %w(osl_valkey osl_valkey_sentinel))
          ).converge(described_recipe)
        end

        before do
          allow(File).to receive(:exist?).and_call_original
          allow(File).to receive(:read).and_call_original
          %w(/etc/valkey/.valkey.conf.chef /etc/valkey/.sentinel.conf.chef).each do |marker|
            allow(File).to receive(:exist?).with(marker).and_return(true)
            allow(File).to receive(:read).with(marker).and_return("0\n")
          end
        end

        it { is_expected.to create_template '/etc/valkey/valkey.conf' }
        it { is_expected.to create_template '/etc/valkey/sentinel.conf' }
      end
    end
  end
end

describe 'valkey_test::sentinel_auth' do
  ALL_PLATFORMS.each do |p|
    context "#{p[:platform]} #{p[:version]}" do
      cached(:chef_run) do
        ChefSpec::SoloRunner.new(
          p.dup.merge(step_into: %w(osl_valkey osl_valkey_sentinel))
        ).converge(described_recipe)
      end

      # Sentinel does support client auth; only clients that cannot send
      # it (tooz) have to go without.
      it do
        is_expected.to create_osl_valkey_sentinel('authlocks').with(
          requirepass: 'sentinel-secret',
          bind: '127.0.0.1'
        )
      end
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^requirepass sentinel-secret$/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^bind 127\.0\.0\.1$/) }
      it { is_expected.to render_file('/etc/valkey/sentinel.conf').with_content(/^protected-mode yes$/) }
      it { is_expected.to_not render_file('/etc/valkey/sentinel.conf').with_content(/^protected-mode no$/) }
    end
  end
end

describe 'valkey_test::replica' do
  ALL_PLATFORMS.each do |p|
    context "#{p[:platform]} #{p[:version]}" do
      cached(:chef_run) do
        ChefSpec::SoloRunner.new(
          p.dup.merge(step_into: %w(osl_valkey))
        ).converge(described_recipe)
      end

      it do
        is_expected.to create_osl_valkey('default').with(
          replicaof: 'valkey1.example.org',
          min_replicas_to_write: 1,
          min_replicas_max_lag: 5
        )
      end
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^replicaof valkey1\.example\.org 6379$/) }
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^min-replicas-to-write 1$/) }
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^min-replicas-max-lag 5$/) }
    end
  end
end

describe 'valkey_test::instances' do
  ALL_PLATFORMS.each do |p|
    context "#{p[:platform]} #{p[:version]}" do
      cached(:chef_run) do
        ChefSpec::SoloRunner.new(
          p.dup.merge(step_into: %w(osl_valkey))
        ).converge(described_recipe)
      end

      it 'converges successfully' do
        expect { chef_run }.to_not raise_error
      end

      it { is_expected.to enable_service 'valkey' }
      it { is_expected.to start_service 'valkey' }
      it { is_expected.to accept_osl_firewall_port('valkey').with(ports: %w(6379)) }
      it { is_expected.to_not accept_osl_firewall_port('valkey-cache') }
      it { is_expected.to accept_osl_firewall_port('valkey-locks').with(ports: %w(6381), osl_only: true) }
      it { is_expected.to apply_sysctl('vm.overcommit_memory').with(value: '1') }
      it { is_expected.to install_package %w(policycoreutils-python-utils setools-console) }
      it do
        is_expected.to create_systemd_unit('valkey@.service').with(
          verify: false,
          content: {
            'Unit' => {
              'Description' => 'Valkey instance %i',
              'After' => 'network.target network-online.target',
              'Wants' => 'network-online.target',
            },
            'Service' => {
              'Type' => 'notify',
              'User' => 'valkey',
              'Group' => 'valkey',
              'WorkingDirectory' => '/var/lib/valkey/%i',
              'ExecStart' => '/usr/bin/valkey-server /etc/valkey/%i.conf --daemonize no --supervised systemd',
              'RuntimeDirectory' => 'valkey-%i',
              'RuntimeDirectoryMode' => '0755',
              'LimitNOFILE' => 10240,
              'Restart' => 'on-failure',
              'RestartSec' => '5s',
            },
            'Install' => {
              'WantedBy' => 'multi-user.target',
            },
          }
        )
      end

      {
        'cache' => 6380,
        'locks' => 6381,
      }.each do |name, port|
        it { is_expected.to manage_selinux_port(port.to_s).with(protocol: 'tcp', secontext: 'redis_port_t') }
        it { is_expected.to create_directory("/var/lib/valkey/#{name}").with(owner: 'valkey', group: 'valkey', mode: '0750') }
        it do
          is_expected.to create_template("/etc/valkey/#{name}.conf").with(
            owner: 'valkey',
            group: 'valkey',
            mode: '0640',
            sensitive: true
          )
        end
        it do
          expect(chef_run.template("/etc/valkey/#{name}.conf")).to \
            notify("service[valkey@#{name}]").to(:restart).immediately
        end
        it { is_expected.to render_file("/etc/valkey/#{name}.conf").with_content(/^port #{port}$/) }
        it { is_expected.to render_file("/etc/valkey/#{name}.conf").with_content(%r{^dir /var/lib/valkey/#{name}$}) }
        it { is_expected.to render_file("/etc/valkey/#{name}.conf").with_content(%r{^logfile /var/log/valkey/#{name}\.log$}) }
        it { is_expected.to create_file("/etc/valkey/.#{name}.conf.chef").with(content: "1\n") }
        it { is_expected.to enable_service "valkey@#{name}" }
        it { is_expected.to start_service "valkey@#{name}" }
      end

      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(%r{^dir /var/lib/valkey$}) }
      it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(%r{^logfile /var/log/valkey/valkey\.log$}) }
      it { is_expected.to render_file('/etc/valkey/cache.conf').with_content(/^maxmemory 64mb$/) }
      it { is_expected.to render_file('/etc/valkey/cache.conf').with_content(/^save ""$/) }
      it { is_expected.to render_file('/etc/valkey/cache.conf').with_content(/^maxmemory-policy allkeys-lru$/) }
      it { is_expected.to render_file('/etc/valkey/locks.conf').with_content(/^requirepass valkey-test$/) }
      it { is_expected.to render_file('/etc/valkey/locks.conf').with_content(/^appendonly yes$/) }
      it { is_expected.to_not render_file('/etc/valkey/locks.conf').with_content(/^save/) }

      it do
        expect(chef_run.node['osl-valkey']['instances'].to_h).to eq(
          'default' => { 'config' => '/etc/valkey/valkey.conf', 'host' => '127.0.0.1', 'port' => 6379 },
          'cache' => { 'config' => '/etc/valkey/cache.conf', 'host' => '127.0.0.1', 'port' => 6380 },
          'locks' => { 'config' => '/etc/valkey/locks.conf', 'host' => '127.0.0.1', 'port' => 6381 }
        )
      end
    end
  end
end

describe 'valkey_test::conflict' do
  platform 'almalinux', '10'
  step_into :osl_valkey

  context 'same unit, different settings' do
    override_attributes['valkey_test']['conflict'] = 'settings'

    it do
      expect { chef_run }.to raise_error(RuntimeError, /osl_valkey: valkey is declared twice with different config$/)
    end
  end

  context 'two units on one port' do
    override_attributes['valkey_test']['conflict'] = 'port'

    it do
      expect { chef_run }.to raise_error(RuntimeError, /osl_valkey: port 6379 is already used by valkey$/)
    end
  end

  context 'an instance named after a packaged file' do
    override_attributes['valkey_test']['conflict'] = 'name'

    it do
      expect { chef_run }.to raise_error(ArgumentError, /osl_valkey: 'sentinel' is not a usable instance name$/)
    end
  end

  context 'an instance name too long for its iptables chain' do
    override_attributes['valkey_test']['conflict'] = 'long'

    it do
      expect { chef_run }.to raise_error(ArgumentError, /'a-name-that-is-22-long' is not a usable instance name$/)
    end
  end

  # osl-haproxy 7.4.0 passes save/maxmemory through config; that must still match
  context 'the same settings spelt two ways' do
    override_attributes['valkey_test']['conflict'] = 'equivalent'

    it { expect { chef_run }.to_not raise_error }
    it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^save ""$/) }
    it { is_expected.to render_file('/etc/valkey/valkey.conf').with_content(/^maxmemory 2gb$/) }
    it { is_expected.to_not apply_sysctl('vm.overcommit_memory') }
    it { expect(chef_run.node['osl-valkey']['instances'].keys).to eq %w(first) }
  end
end

describe 'valkey_test::delete' do
  platform 'almalinux', '10'
  step_into :osl_valkey

  %w(valkey valkey@gone).each do |unit|
    it { is_expected.to stop_service unit }
    it { is_expected.to disable_service unit }
  end
  it { is_expected.to delete_file '/etc/valkey/.valkey.conf.chef' }
  it { is_expected.to delete_file '/etc/valkey/.gone.conf.chef' }
  it { is_expected.to delete_file '/etc/valkey/gone.conf' }
  it { is_expected.to_not delete_file '/etc/valkey/valkey.conf' }
  it { is_expected.to delete_file '/etc/systemd/system/valkey.service.d/restart.conf' }
  it do
    expect(chef_run.file('/etc/systemd/system/valkey.service.d/restart.conf')).to \
      notify('execute[valkey: daemon-reload]').to(:run).immediately
  end
  it { is_expected.to_not install_package 'valkey' }
end
